create table if not exists public.pending_outreach_leads (
  id bigint generated by default as identity primary key,
  token text not null unique,
  status text not null default 'pending',
  lead_source text not null,
  lead_id text not null,
  business_name text not null,
  recipient_emails text not null,
  imported_email text not null default '',
  phone text not null default '',
  website text not null default '',
  external_lead_id text not null default '',
  scanner_batch_id text not null default '',
  scanner_lead_business_id text not null default '',
  selected_matches_json jsonb not null default '[]'::jsonb,
  subject text not null default '',
  message_id text not null default '',
  sent_at text not null default '',
  confirmed_matches_json jsonb not null default '[]'::jsonb,
  rejected_matches_json jsonb not null default '[]'::jsonb,
  confirmed_at text not null default '',
  cms_claim_id text not null default '',
  cms_intake_id text not null default '',
  cms_dashboard_url text not null default '',
  cms_response_json jsonb not null default '{}'::jsonb,
  conversion_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pending_outreach_leads_lead_idx
on public.pending_outreach_leads (lead_source, lead_id);

create index if not exists pending_outreach_leads_status_idx
on public.pending_outreach_leads (status);

create index if not exists pending_outreach_leads_token_idx
on public.pending_outreach_leads (token);

grant usage on schema public to service_role;
grant select, insert, update, delete on public.pending_outreach_leads to service_role;
grant usage, select on sequence public.pending_outreach_leads_id_seq to service_role;
